AllCops:
  Include:
    - 'lib/**/*'
    - 'bin/*'
    - 'exe/*'
    - 'test/**/*.rb'
  Exclude:
    - 'bin/setup'

Style/FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

# Using %[...] to avoid conflicts with parens in shell expansions
Style/PercentLiteralDelimiters:
  Exclude:
    - 'test/**/*_test.rb'
    - 'test/**/*_tests.rb'

# Need trailing whitespace for some test suites
Layout/TrailingWhitespace:
  Exclude:
    - 'test/**/*_test.rb'
    - 'test/**/*_tests.rb'

Metrics/ParameterLists:
  Exclude:
    - 'test/lib/slightish_test.rb'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false


# Ideally these are TODOs:

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
